asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleMetadataBuilder.cs
asset-bundle-converter/Assets/AssetBundleConverter/Utils.cs

Some tiding up was required when using _platform.
1) For shader dependencies, the `_platform` was required to standardize the way we search the asset bundle in the ECS project.
2) I had to remove the `_platform` when writing the metadata file in the downloaded folder. I could have added the `_platform` in the Downloaded platform path, but going this way seemed cleaner since I didnt find a standarize path that I could touch

fix: adding metadata for standalone platforms

---

asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleSceneConversionWindow.cs
asset-bundle-converter/Assets/AssetBundleConverter/SceneClient.cs
asset-bundle-converter/Assets/AssetBundleConverter/Utils.cs

Empty parcels are defined by `mapping.json` and loaded by Kernel. GLTF assets exist in the `unity-renderer` repo but they are not converted to ABs.
Since `Explorer-Alpha` does not work with GLTF directly this small addition allows to convert all empty scenes with one click.

feat: Add a possibility to convert empty parcels from the Editor

---

Dockerfile
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.asmdef
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleSceneConversionWindow.cs
asset-bundle-converter/Assets/AssetBundleConverter/ClientSettings.cs
asset-bundle-converter/Assets/AssetBundleConverter/Config.cs
asset-bundle-converter/Assets/AssetBundleConverter/Environment.cs
asset-bundle-converter/Assets/AssetBundleConverter/SceneClient.cs
asset-bundle-converter/Assets/AssetBundleConverter/Tests/AssetBundleConverterShould.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/ScriptableBuildPipeline.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/ScriptableBuildPipeline.cs.meta
asset-bundle-converter/Packages/manifest.json
asset-bundle-converter/Packages/packages-lock.json

All material keywords are not saved in ABs
Unfortunately, it's another [nasty Unity bug](https://issuetracker.unity3d.com/issues/assetbundles-shader-keyword-is-lost-in-build-when-shader-is-in-different-assetbundle-than-material) :facepalm: Emission and Normal map keywords are not saved either.
SHADER KEYWORD IS LOST IN BUILD WHEN SHADER IS IN DIFFERENT ASSETBUNDLE THAN MATERIAL
Perfectly describes the situation.
The reason why it works in the old renderer is because they do this manually:
public static void OptimizeMaterial(Material material)
{
//NOTE(Brian): Just enable these keywords so the SRP batcher batches more stuff.
material.EnableKeyword("_EMISSION");
material.EnableKeyword("_NORMALMAP");
if (!material.IsKeywordEnabled("_ALPHATEST_ON") && material.HasProperty(ShaderUtils.Cutoff)) …

fix: Switch to Scriptable Build Pipeline

---

Dockerfile
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/ScriptableBuildPipeline.cs

- Scriptable pipeline had a wrong settings which added more than 1 gameobject to the assetbundle. That was corrected
- Removed mac from restricited platforms

fix: scriptable pipeline adding more thhan one gameobject

---

asset-bundle-converter/Assets/AssetBundleConverter/Tests/AssetBundleConverterShould.cs

(instantiation of a copy no longer calls AssetDatabase)

Fix: MaterialExtracted test

---

asset-bundle-converter/Assets/AssetBundleConverter/LODsConverter/Scripts/LODConversion.cs

If there is a `_Downloaded` path lingering from the regular asset bundle converter process, it deletes it for the lods process

fix: delete downloaded folder in lods process

---

.gitignore
asset-bundle-converter/Assets/AssetBundleConverter/LODsConverter/Editor/CustomLODFBXPostProcessor.cs
asset-bundle-converter/Assets/AssetBundleConverter/LODsConverter/Editor/CustomLODFBXPostProcessor.cs.meta
asset-bundle-converter/Assets/AssetBundleConverter/LODsConverter/Editor/LODClient.cs
asset-bundle-converter/Assets/AssetBundleConverter/LODsConverter/Scripts/LODConversion.cs
asset-bundle-converter/Assets/AssetBundleConverter/LODsConverter/Utils/LODPathHandler.cs

- Enforces BC7 texturing for lods higher than 0
- Set TexArray material into the asset bundle
- Removed the creation of unncesary prefab
- Adds a post processor to generator colliders on lod 0

feat: lod texture enforcer

---

asset-bundle-converter/ProjectSettings/GraphicsSettings.asset

- Sets exponential fog (the one used in alpha) as default
- Sets unity-shared-dependencies to latest main

chore: shared dependecies cleanup

---

asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs

Scene emotes were converted to legacy form, which is not supported in explorer-alpha. This change forces to convert all emotes to mecanim when the target is either windows or osx.

fix: convert mecanim anims on standalone target

---

Dockerfile
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs

It is required that two animations play simultaneously on a single animator as it is described here: https://github.com/decentraland/unity-explorer/issues/1087
Directly related to this pr: https://github.com/decentraland/unity-explorer/pull/1369
Therefore, it is needed to provide a layer to each state, so we can set a weight on each layer.

feat: anim layers

---

asset-bundle-converter/.idea/.idea.asset-bundle-converter/.idea/.gitignore
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.asmdef
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleSceneConversionWindow.cs
asset-bundle-converter/Assets/AssetBundleConverter/ClientSettings.cs
asset-bundle-converter/Assets/AssetBundleConverter/ConversionState.cs
asset-bundle-converter/Assets/AssetBundleConverter/ConversionState.cs.meta
asset-bundle-converter/Assets/AssetBundleConverter/Editor/CustomGltfImporter.cs
asset-bundle-converter/Assets/AssetBundleConverter/ErrorCodes.cs
asset-bundle-converter/Assets/AssetBundleConverter/ErrorCodes.cs.meta
asset-bundle-converter/Assets/AssetBundleConverter/Persistence.meta
asset-bundle-converter/Assets/AssetBundleConverter/Persistence/Persistence.asmdef
asset-bundle-converter/Assets/AssetBundleConverter/Persistence/Persistence.asmdef.meta
asset-bundle-converter/Assets/AssetBundleConverter/Persistence/PersistentSetting.cs
asset-bundle-converter/Assets/AssetBundleConverter/Persistence/PersistentSetting.cs.meta
asset-bundle-converter/Assets/AssetBundleConverter/SceneClient.cs
asset-bundle-converter/Assets/AssetBundleConverter/Utils.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/GltFastFileProvider.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Interfaces/IGltfImport.cs

Fixes https://github.com/decentraland/unity-explorer/issues/1291
* Introduced 5% tolerance for failing conversion
* Introduced downloading in batches to prevent SSL error
* Introduced persistent settings to save parameters of the conversion window into Editor Prefs
* Introduced partial downloading till completion instead of full clean-up, useful for debugging/testing with a lot of required assets for the scene

Fix: Conversion failure

---

Dockerfile
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs

As it is described in this issue: https://github.com/decentraland/unity-explorer/issues/1376
The doors should stay at the last frame of its open animation when the state is `loop:false`.
By setting the empty state to not override the bone defaults, the animation state will keep its latest state when transitions to `empty`.

fix: dont override anim defaults

---

asset-bundle-converter/Assets/AssetBundleConverter/LODsConverter/Scripts/LODConversion.cs
consumer-server/src/logic/run-conversion.ts

- Sets a clean state for asset bundle conversion. Some conversions were falling because old dirty and broken assets where still in the instance

fix: Cleanup folder before conversion

---

asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs

In order to properly export the animator generated for an animated asset, we need to add the layer state machine into the animator asset file. This will allow to export->import the asset in the explorer so it can be debugged in real game runtime.

fix: add layer state machine into animator asset

---

asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs
asset-bundle-converter/Assets/AssetBundleConverter/Utils.cs

Fixes #1502 (https://github.com/decentraland/unity-explorer/issues/1502)
The scene was not converted due to a `Unsupported texture format - Texture2D::EncodeTo functions do not support compressed texture formats.` exception
According to [Unity Docs](https://docs.unity3d.com/ScriptReference/ImageConversion.EncodeToPNG.html), `EncodeToPNG()` does not work with compressed formats. This PR catches that exception

fix: catch texture compressed formats

---

asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs
asset-bundle-converter/Assets/AssetBundleConverter/ClientSettings.cs

- Force unload of unnecessary resources after iterating each gltf
- `placeOnScene` is now off by default when not using the converter window.

chore: unload optimization

---

asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/Directory.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Interfaces/IDirectory.cs
consumer-server/src/logic/conversion-task.ts

Apparently the default directory removal used in unity was working for windows but not for mac, this approach ensures that the deletion also removes all the files in the folder to work regardless of the platform

fix: fixed directory removal

---

Dockerfile
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/ScriptableBuildPipeline.cs

The dependencies were wrongly removed from the build. We need them to build, if they don't, Unity forceably includes all shaders into ALL ABs.

fix: rebuild dependencies

---

asset-bundle-converter/Assets/AssetBundleConverter/Editor/CustomGltfImporter.cs
asset-bundle-converter/Assets/AssetBundleConverter/VisualTests.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/AssetBundleConverterMaterialGenerator.cs
asset-bundle-converter/Assets/AssetBundleConverter/Wrappers/Implementations/Default/DefaultGltfImporter.cs

Fixes the SRP Batcher Helper Optimisations from causing problems on the new Explorer platform but avoids making changes to the older renderer.

fix: SRPBatchingHelper OptimizeMaterial only affect WebGL target

---

Dockerfile
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs

This PR improves the processing of the animation clips by speeding up the reading of the layer names via cache and fixed the import of duplicated animation clips

fix: fixed import of duplicated animation clips

---

consumer-server/src/logic/conversion-task.ts

Reverts the conversion task changes to verify content changes to avoid the issue of previously converted ABs to be loaded with errors if there were any

fix: reverted mitigation for manifest

---

consumer-server/src/logic/has-content-changed-task.ts

- Adds a fake param to ignore the cache when resolving `hasContentChanged`. This will stop the CDN to return a cached value when two conversions are compared the same day

fix: Add cache ignore in hasContentChanged

---

asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleSceneConversionWindow.cs
asset-bundle-converter/Assets/AssetBundleConverter/ClientSettings.cs

- Removes the strict error policy that made a scene conversion failed if more than 5% of assets failed. 
- That policy is gone. Now any amount of assets can fail, and the scene will still be converted
- It will keep a error code `12` nonetheless

fix: Remove strict error policy

---

Dockerfile
asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs

This PR forces scene emotes to be processed as mecanim animations, like it is already done with the regular AB emotes.
To do it I've simply moved the creation of import settings to be generated on a gltf basis, forcing the animation method on assets containing emotes ending in "_emote.glb" as suggested in https://github.com/decentraland/unity-explorer/issues/3455

fix: added support for mecanim scene emotes conversion

---

asset-bundle-converter/Assets/AssetBundleConverter/AssetBundleConverter.cs

Fix https://github.com/decentraland/unity-explorer/issues/2804
this PR prevents adding animations for wearable types

fix: do not allow animation for wearable types
